experiment_id: xs_1a_logen_bikes_cleaned_gen_999
experiment_root_dir: /home/ekirby/scania/ekirby/datasets/nuscenes_generated_bikes/xs_1a_logen_bikes_cleaned_gen_999
objects_to_test: generated
test_split: train
filtered_instance_ids: null
batch_size: 16
class_name: vehicle.bicycle