experiment_id: xs_1a_self_voxel_4ch_gen_b16
experiment_root_dir: nuscenes_generated_bikes/xs_1a_self_voxel_4ch_gen_b16
objects_to_test: generated
test_split: val
filtered_instance_ids: null
batch_size: 16
