experiment_id: xs_1a_logen_traffic_cones_gen
experiment_root_dir: nuscenes_generated_bikes/xs_1a_logen_traffic_cones_gen
objects_to_test: generated
test_split: val
filtered_instance_ids: null
batch_size: 16
class_name: movable_object.trafficcone
